name = "ini"
grammar = "ini"
path_suffixes = [
    "ini",
    "conf",
    "cfg",
    "config",
    ".editorconfig",
    "automount",
    "mount",
    "path",
    "scope",
    "service",
    "slice",
    "socket",
    "swap",
    "target",
    "timer",
    "container",
    "volume",
    "network",
    "kube",
    "image",
    "build",
    "pod",
]
line_comments = ["; ", "# "]
autoclose_before = ":.,=}])>"
brackets = [
    { start = "[", end = "]", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
]
