id = "ini"
name = "ini"
version = "0.0.6"
schema_version = 1
description = "Support for ini and related config files (ini, conf, cfg, config, editorconfig) and systemd unit files (automount, mount, path, scope, service, slice, socket, swap, target, timer)"
repository = "https://github.com/bajrangCoder/zed-ini"
authors = ["Raunak Raj <bajrangcoders@gmail.com>"]
themes = []
icon_themes = []
languages = ["languages/ini"]
capabilities = []

[lib]

[grammars.ini]
repository = "https://github.com/justinmk/tree-sitter-ini"
rev = "32b31863f222bf22eb43b07d4e9be8017e36fb31"

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
